User: oiolen
IdentityFile: ~/.ssh/id_ed25519
ServerAliveInterval: 240
ServerAliveCountMax: 2
ControlPath: ~/.ssh/sockets/%r@%h:%p
ControlMaster: auto
ProxyJumpDefault: ssh.ult

hostnames:
  telenor.net:
    NoProxyJump: True
    hosts:
      ssh.ult:

  bandak.nsc.no:
    hosts:
      mapr01:
      mapr02:
      mapr03:
      mapr04:
      mapr05:
      mapr06:
      mapr07:
      mapr08:
      edge-usr01:
      edge-eng01:
      edge-eng02:
      s-mapr01:
      s-mapr02:
      s-mapr03:
      s-mapr04:
      s-mapr05:
      s-edge-usr01:
      s-edge-eng01:
      s-edge-eng02:
      s-edge-eng03:
      bandak-ansible01:

  nsc.no:
    hosts:
      nest-git01:
        Port: 2222
        User: git

vips:
  superset.bandak.nsc.no:
  s-superset.bandak.nsc.no:
  trino.bandak.nsc.no:
  zeppelin.bandak.nsc.no:
  s-zeppelin.bandak.nsc.no:
  s-airflow.bandak.nsc.no:
  airflow.bandak.nsc.no:
  db-browser.bandak.nsc.no:
  vault.bandak.nsc.no:
  yarn-applications.bandak.nsc.no:
  spark-history.bandak.nsc.no:
  nexus.bandak.nsc.no:
  kubeflow.bandak.nsc.no:
  harbor.nest.nsc.no:
  nest-git01.nsc.no:
