User: oiolen
IdentityFile: ~/.ssh/id_ed25519
ServerAliveInterval: 240
ServerAliveCountMax: 2
ControlPath: ~/.ssh/sockets/%r@%h:%p
ControlMaster: auto
ProxyJumpDefault: ssh.ult

hostnames:
  
  telenor.net:
    DynamicForward: 1080
    NoProxyJump: True
    hosts:
      ssh.ult:

  bandak.nsc.no:
    DynamicForward: 1300
    hosts:
      mapr01:
      mapr02:
      mapr03:
      mapr04:
      mapr05:
      mapr06:
      mapr07:
      mapr08:
      edge-usr01:
      edge-eng01:
      edge-eng02:
      s-mapr01:
      s-mapr02:
      s-mapr03:
      s-mapr04:
      s-mapr05:
      s-edge-usr01:
      s-edge-eng01:
      s-edge-eng02:
      s-edge-eng03:
      bandak-ansible01:

  nsc.no:
    hosts:
      nest-git01:
        Port: 2222
        User: git
