#!/bin/zsh

if [ -z "$1" ]; then
  echo "Filename required"
  exit 1
fi

folder=$(find $OBSIDIAN_VAULT -mindepth 1 -maxdepth 1 -type d ! -path '*/.*' | sort -r | fzf)

if [[ -z $folder ]]; then
    exit 0
fi

file_name=$folder/$(echo "$1" | tr ' ' '-').md

tmux_running=$(pgrep tmux)

SESSION="obsidian"

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $SESSION -c $SESSION
    exit 0
fi

if ! tmux has-session -t=$SESSION 2> /dev/null; then
    tmux new-session -ds $SESSION -c $SESSION
fi

tmux send-keys -t $SESSION "cd $OBSIDIAN_VAULT" C-m
tmux send-keys -t $SESSION "vim $file_name" C-m
tmux send-keys -t $SESSION ":w" C-m
tmux switch-client -t $SESSION
