#!/bin/zsh

tmux_running=$(pgrep tmux)

SESSION="obsidian"

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $SESSION -c $SESSION
    exit 0
fi

if ! tmux has-session -t=$SESSION 2> /dev/null; then
    tmux new-session -ds $SESSION -c $SESSION
fi

file_name=$(echo "$1" | tr ' ' '-').md

tmux send-keys -t $SESSION "cd $OBSIDIAN_VAULT" C-m
tmux send-keys -t $SESSION "vim ." C-m
tmux switch-client -t $SESSION


