#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/development -mindepth 2 -maxdepth 2 -type d | fzf --padding 1,2)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux new-window -n "$(basename "$selected")" -c "$selected"
