tmux:
  symbols:
    branch: " "
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: "… "
    stashed: "⚑ "
    insertions: "Σ "
    deletions: "Δ "
    clean: "✔"
  styles:
    clear:      "#[fg=#d4be98,bg=#4F4946]"
    state:      "#[fg=#d4be98]"
    branch:     "#[fg=#d4be98]"
    remote:     "#[fg=#d4be98]"
    divergence: "#[fg=#d4be98]"
    staged:     "#[fg=#d4be98]"
    conflict:   "#[fg=#d4be98]"
    modified:   "#[fg=#d4be98]"
    untracked:  "#[fg=#d4be98]"
    stashed:    "#[fg=#d4be98]"
    insertions: "#[fg=#d4be98]"
    deletions:  "#[fg=#d4be98]"
    clean:      "#[fg=#d4be98]"
  layout: [branch, " #[fg=#d4be98,bg=#4F4946] #[fg=#d4be98,bg=#4F4946]", flags]
  options:
    branch_max_len: 24
    branch_format: ""
    ellipsis: "…"
    hide_clean: false
    swap_layout: false
