#Zinit Plugin Manager
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"


#Powerlevel10k
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH=$HOME/.config/zsh
export OBSIDIAN_VAULT=$HOME/obsidian/oleenger
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH" 
export PATH="$HOME/.config/scripts/:$PATH" 
export PATH="$HOME/.local/bin:$PATH"

#Themes
export BAT_THEME="Visual Studio Dark+"

#Imports
source $ZSH/imports/powerlevel10k.zsh
source $ZSH/imports/history.zsh
source $ZSH/imports/functions.zsh
source $ZSH/imports/git.zsh
source $ZSH/imports/fzf.zsh
source $ZSH/imports/zoxide.zsh

#Plugins
zinit ice depth=1

# zinit light zsh-users/zsh-autosuggestions
#ZSH_AUTOSUGGEST_STRATEGY='history'
# # bindkey '^I' autosuggest-accept
# bindkey '^ ' autosuggest-execute

zinit light zdharma-continuum/fast-syntax-highlighting
zinit light jeffreytse/zsh-vi-mode
# zinit light marlonrichert/zsh-autocomplete

# zinit load atuinsh/atuin
# export ATUIN_NOBIND="true"
# eval "$(atuin init zsh --disable-ctrl-r)"
# eval "$(atuin init zsh)"

# Yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

#Aliases
source $ZSH/imports/aliases.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

bindkey -v

function sesh-sessions() {
  {
    exec </dev/tty
    exec <&1
    local session
    session=$(sesh list -t -c | fzf --height 40% --reverse --border-label ' sesh ' --border --prompt '⚡  ')
    zle reset-prompt > /dev/null 2>&1 || true
    [[ -z "$session" ]] && return
    sesh connect $session
  }
}

zle     -N             sesh-sessions
bindkey '^s' sesh-sessions

export PATH="$PATH:/Users/t927604/.local/bin"
