export ZSH=$HOME/.config/zsh

#Homebrew
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH" 

#Themes
export BAT_THEME="Visual Studio Dark+"

#Imports
source $ZSH/imports/powerlevel10k.zsh
source $ZSH/imports/history.zsh
source $ZSH/imports/functions.zsh
source $ZSH/imports/fzf.zsh
source $ZSH/imports/zoxide.zsh

#Plugins
source $ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/plugins/zsh-eza/zsh-eza.plugin.zsh

#Aliases
source $ZSH/imports/aliases.zsh
