alias mkd_table_formatter="markdown-table-formatter -p 0"
alias conf="cd $HOME/.config/"
alias ls="eza --icons=always"
alias vim="nvim"
alias vvim="/usr/bin/vim"
alias cat="bat"
alias ll="ls -alh"
alias gs="git status"
alias reload-zsh="source ~/.zshrc"
alias edit-zsh="nvim ~/.zshrc"
alias find="fd"
alias cd="z"
